name: Test on CentOS 7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: centos-7
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo yum install -y <dependencies>
      - name: Run tests
        run: |
          python3 -m unittest discover