name: Test on CentOS 7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CentOS 7 container
        run: |
          docker run --rm -v $(pwd):/code -w /code centos:7 bash -c "
          yum install -y epel-release;
          yum update -y;
          yum install -y python3 python3-pip git bash sudo rocksdb-devel gcc gcc-c++ make;
          python3 -m pip install --upgrade pip;
          python3 -m pip install rocksdb;
          cd /code;
          python3 -m unittest discover"
