name: Test on Debian Buster

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: debian:buster
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y <dependencies>
      - name: Run tests
        run: |
          python3 -m unittest discover
