name: Test on Debian Stretch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Debian Stretch container
        run: |
          docker run --rm -v $(pwd):/code -w /code debian:stretch bash -c "
          apt-get update && apt-get install -y python3 python3-pip git bash sudo librocksdb-dev build-essential;
          python3 -m pip install --upgrade pip;
          python3 -m pip install rocksdb;
          python3 -m unittest discover"
