name: Test on Debian Stretch (Archive)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Debian Stretch container (Archive)
        run: |
          docker run --rm -v $(pwd):/code -w /code debian:stretch bash -c "
          sed -i 's|http://deb.debian.org/debian|http://archive.debian.org/debian|g' /etc/apt/sources.list;
          sed -i 's|http://security.debian.org/debian-security|http://archive.debian.org/debian-security|g' /etc/apt/sources.list;
          apt-get update && apt-get install -y python3 python3-pip git bash sudo librocksdb-dev build-essential;
          python3 -m pip install --upgrade pip;
          python3 -m pip install rocksdb;
          python3 -m unittest discover"
