name: Test on Ubuntu 18.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 \
            python3-pip \
            git \
            librocksdb-dev \
            build-essential
          python3 -m pip install --upgrade pip
          python3 -m pip install rocksdb

      - name: Run tests
        run: |
          python3 -m unittest discover
