name: Test on Ubuntu 22.04

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 \
            python3-pip \
            git \
            librocksdb-dev \
            build-essential \
            cmake \
            g++  # Added cmake and g++ for building dependencies
          python3 -m pip install --upgrade pip

      - name: Install Cython
        run: |
          python3 -m pip install --upgrade cython  # Ensure Cython is up-to-date

      - name: Install Python libraries
        run: |
          python3 -m pip install rocksdb  # Install the Python rocksdb package

      - name: Run tests
        run: |
          python3 -m unittest discover
